language: node_js
sudo: required
node_js: stable

cache:
  directories:
    - node_modules

branches:
  only:
    - hexo

before_install:
  - npm install -g hexo-cli

install:
  - npm install
  - npm install hexo-deployer-git --save

script:
  - hexo clean && hexo g

after_script:
  - git config user.name "chowyi"
  - git config user.email "3964769+chowyi@users.noreply.github.com"
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - hexo d
