name: Clean, Generate and Deploy Hexo

on:
  push:
    branches: 
      - hexo

jobs:
  publish:
    name: Hexo Auto-Deploy by GitHub Actions
    runs-on: ubuntu-latest
    steps:
    - name: 1. git checkout...
      uses: actions/checkout@v1
    
    - name: 2. setup nodejs...
      uses: actions/setup-node@v1
      
    - name: 3. install hexo...
      run: sudo npm install -g hexo-cli
      
    - name: 4. install dependencies...
      run: |
        npm install
        npm install hexo-deployer-git --save
        
    - name: 5. clean and generate public files...
      run: hexo clean && hexo g
      
    - name: 6. configure git...
      env:
        GH_TOKEN: ${{secrets.ACTIONS_TOKEN}}
      run: |
        git config --global user.name "Chowyi"
        git config --global user.email "3964769+chowyi@users.noreply.github.com"
        sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
        
    - name: 7. deploy...
      run: sudo hexo d
